version: '3'

services:
  postgres-database:
    image: postgres
    container_name: ribeiros-events-database
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"