spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION_STRING:jdbc:postgresql://localhost:15432/ribeiros-events}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
ribeiros-events:
  jwt-expiration: ${JWT_TOKEN_EXPIRATION:3600000}
  jwt-secret: ${JWT_TOKEN_SECRET:uk2%81b#s01287@8sbakn!-29nsh12}
